mex -largeArrayDims -I/home/lino/Documents/BA/ecos-master/external/CHOLMOD/Include -I/home/lino/Documents/BA/ecos-master/include... 
    -I/home/lino/Documents/BA/ecos-master/external/amd/include -I/home/lino/Documents/BA/ecos-master/external/ldl/include...
    -I/home/lino/Documents/BA/ecos-master/external/SuiteSparse_config -L/home/lino/Documents/BA/ecos-master/external/CHOLMOD/Lib...
    -L/home/lino/Documents/BA/ecos-master/external/AMD/Lib -L/home/lino/Documents/BA/ecos-master/external/COLAMD/Lib -L/home/lino/Documents/BA/ecos-master/external/SuiteSparse_config...
    -L/home/lino/Documents/BA/ecos-master/external/SuiteSparse_config/xerbla -L/home/lino/Documents/BA/ecos-master/external/CAMD/Lib...
    -L/home/lino/Documents/BA/ecos-master/external/CCOLAMD/Lib -lcholmod -lamd -lcolamd -lsuitesparseconfig -lcerbla -lmetis -lcamd -lccolamd -lm -lgoto2 -llapack...
    factor_solve_mex.c lino_kkt.c cone.c splamm.c spla.c timer.c